"""empty message

Revision ID: 98c756455ee7
Revises: 1691e127b581
Create Date: 2022-09-12 17:03:13.680186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98c756455ee7'
down_revision = '1691e127b581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('anonymous', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'anonymous')
    # ### end Alembic commands ###
